# This file stores configurations for your Shopify app.

name = "Mouse Whisperer"
client_id = "be249e7dc1288f980804d0bf5e40cde0"
application_url = "https://mousewhisperer.vercel.app"
embedded = true

[access_scopes]
scopes = "read_products,write_pixels,read_customer_events"

[auth]
redirect_urls = ["https://mousewhisperer.vercel.app/auth/callback"]

[app_proxy]
url = "https://mousewhisperer.vercel.app/api/track"
subpath = "api"
prefix = "apps"

[webhooks]
api_version = "2024-10"

  # Handled by: /app/routes/webhooks.app.uninstalled.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  # Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # Webhooks can have filters
  # Only receive webhooks for product updates with a product price >= 10.00
  # See: https://shopify.dev/docs/apps/build/webhooks/customize/filters
  # [[webhooks.subscriptions]]
  # topics = ["products/update"]
  # uri = "/webhooks/products/update"
  # filter = "variants.price:>=10.00"

  # Mandatory compliance topics for public apps
  # See: https://shopify.dev/docs/apps/build/privacy-law-compliance
  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = ["customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = ["shop/redact"]
