api_version = "2024-10"

[[extensions]]
type = "web_pixel"
name = "Conversion Tracker"
handle = "tracking-pixel"

runtime_context = "strict"

[extensions.settings]
  [[extensions.settings.fields]]
  key = "apiEndpoint"
  name = "API Endpoint"
  description = "The endpoint to send conversion data to"
  type = "single_line_text_field"

[[extensions.targeting]]
condition = "true"
