api_version = "2024-10"

[[extensions]]
uid = "5d23d7eb-259c-2ecc-9355-3be596a7ce72d9323f16"
type = "web_pixel"
name = "Conversion Tracker"
handle = "tracking-pixel"

runtime_context = "strict"

[extensions.settings]
type = "object"

[extensions.settings.fields]

[extensions.settings.fields.apiEndpoint]
name = "API Endpoint"
description = "The endpoint to send conversion data to"
type = "single_line_text_field"

[[extensions.targeting]]
condition = "true"
